CREATE TABLE IF NOT EXISTS `vdc_bill`.`user_item_record_%s` (
  `UpdateTime` datetime DEFAULT '0000-00-00 00:00:00' COMMENT '发生时间',
  `TransID` varchar(128) DEFAULT '' COMMENT '账单号',
  `CauseID` int(10) DEFAULT '0' COMMENT '更新原因',
  `RoomName` varchar(128) DEFAULT '' COMMENT '房间名',
  `RoomID` int(10) DEFAULT '0' COMMENT '房间号',
  `ItemType` int(4) DEFAULT '0' COMMENT '道具类型',
  `ItemName` varchar(128) DEFAULT '' COMMENT '道具名',
  `ItemID` int(10) DEFAULT '0' COMMENT '道具id',
  `ItemPrice` int(10) DEFAULT '0' COMMENT '道具价格',
  `ItemCount` int(10) DEFAULT '0' COMMENT '道具数量',
  `Benifit` int(10) DEFAULT '0' COMMENT '受赠者收益',
  `SrcRoleName` varchar(128) DEFAULT '' COMMENT '赠送者昵称',
  `SrcRoleID` int(10) DEFAULT '0' COMMENT '赠送者角色id',
  `SrcAccountID` int(10) DEFAULT '0' COMMENT '赠送者数字账号',
  `SrcVipLevel` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT '赠送者VIP等级',
  `SrcLeftMoney` int(10) DEFAULT '0' COMMENT '赠送者剩余钱币',
  `DstRoleName` varchar(128) DEFAULT '' COMMENT '受赠者昵称',
  `DstRoleID` int(10) DEFAULT '0' COMMENT '受赠者角色id',
  `DstAccountID` int(10) DEFAULT '0' COMMENT '受赠者数字账号',
  `DstVipLevel` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT '收赠者VIP等级',
  `DstLeftMoney` int(10) DEFAULT '0' COMMENT '收赠者剩余钱币',
  `Time` int(11) DEFAULT '0' COMMENT '入库时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
